ALTER TYPE "IntegrationProvider" ADD VALUE IF NOT EXISTS 'POSTHOG';
ALTER TYPE "IntegrationProvider" ADD VALUE IF NOT EXISTS 'LINEAR';
ALTER TYPE "IntegrationProvider" ADD VALUE IF NOT EXISTS 'GITHUB';
ALTER TYPE "IntegrationProvider" ADD VALUE IF NOT EXISTS 'UNIFY';
