ALTER TYPE "IntegrationProvider" ADD VALUE IF NOT EXISTS 'META_ADS';
ALTER TYPE "IntegrationProvider" ADD VALUE IF NOT EXISTS 'META_PAGE';
ALTER TYPE "IntegrationProvider" ADD VALUE IF NOT EXISTS 'PYLON';
