ALTER TYPE "IntegrationProvider" ADD VALUE IF NOT EXISTS 'GOOGLE_ADS';
ALTER TYPE "IntegrationProvider" ADD VALUE IF NOT EXISTS 'META';
ALTER TYPE "IntegrationProvider" ADD VALUE IF NOT EXISTS 'PYLON';
