import type { RuleDescriptor } from "@/components/settings/integrations/types";

export const TASK_STATUS_OPTIONS = [
  { label: "Queued", value: "QUEUED" },
  { label: "Active", value: "ACTIVE" },
  { label: "Not Done", value: "NOT_DONE" },
] as const;

export const RANGE_PRESET_OPTIONS = [
  { label: "Last 7 days", value: "7d" },
  { label: "Last 30 days", value: "30d" },
  { label: "Last 90 days", value: "90d" },
] as const;

export const RULE_DESCRIPTORS: RuleDescriptor[] = [
  {
    id: "gmail-capture",
    provider: "google-workspace",
    title: "Gmail Commitment Capture",
    ruleKey: "gmail_commitment_capture",
    endpoint: "/api/integrations/google-workspace/gmail-capture",
    runAction: "sync",
    supportsDryRun: true,
    supportsStatusOverride: true,
    editorType: "generic",
    fields: [
      { key: "label", label: "Label", type: "text", description: "Only threads with this Gmail label are considered." },
      { key: "includeStarred", label: "Include Starred", type: "boolean" },
      { key: "maxResults", label: "Max Results", type: "number", min: 1, max: 100 },
    ],
  },
  {
    id: "drive-comment-escalation",
    provider: "google-workspace",
    title: "Drive Comment Escalation",
    ruleKey: "google_drive_comment_escalation",
    endpoint: "/api/integrations/google-workspace/drive-comment-escalation",
    runAction: "sync",
    supportsDryRun: true,
    supportsStatusOverride: true,
    editorType: "generic",
    fields: [
      { key: "folderIds", label: "Folder IDs", type: "string-list", description: "One folder ID per line." },
      { key: "maxFilesPerRun", label: "Max Files Per Run", type: "number", min: 1, max: 500 },
      { key: "maxCommentsPerFile", label: "Max Comments Per File", type: "number", min: 1, max: 500 },
      { key: "dueInHours", label: "Due In Hours", type: "number", min: 1, max: 240 },
      { key: "requireAssignment", label: "Require Assignment", type: "boolean" },
      { key: "reviewKeywords", label: "Review Keywords", type: "string-list", description: "One keyword or phrase per line." },
    ],
  },
  {
    id: "drive-transcript-capture",
    provider: "google-workspace",
    title: "Drive Transcript Capture",
    ruleKey: "google_drive_transcript_capture",
    endpoint: "/api/integrations/google-workspace/drive-transcript-capture",
    runAction: "sync",
    supportsDryRun: true,
    supportsStatusOverride: true,
    editorType: "generic",
    fields: [
      { key: "folderIds", label: "Folder IDs", type: "string-list", description: "One transcript folder ID per line." },
      { key: "lookbackHours", label: "Lookback Hours", type: "number", min: 1, max: 336 },
      { key: "filenameKeywords", label: "Filename Keywords", type: "string-list", description: "One keyword or phrase per line." },
      { key: "maxFilesPerRun", label: "Max Files Per Run", type: "number", min: 1, max: 500 },
    ],
  },
  {
    id: "calendar-followup",
    provider: "google-workspace",
    title: "Calendar Prep + Follow-up",
    ruleKey: "google_calendar_prep_followup",
    endpoint: "/api/integrations/google-workspace/calendar-followup",
    runAction: "sync",
    supportsDryRun: true,
    supportsStatusOverride: true,
    editorType: "generic",
    fields: [
      { key: "calendarIds", label: "Calendar IDs", type: "string-list", description: "Use `primary` or specific calendar IDs." },
      { key: "prepLeadHours", label: "Prep Lead Hours", type: "number", min: 1, max: 96 },
      { key: "followupDelayMinutes", label: "Follow-up Delay Minutes", type: "number", min: 0, max: 1440 },
      { key: "lookaheadHours", label: "Lookahead Hours", type: "number", min: 1, max: 240 },
      { key: "lookbackHours", label: "Lookback Hours", type: "number", min: 1, max: 240 },
    ],
  },
  {
    id: "hubspot-stage-checklist",
    provider: "hubspot",
    title: "HubSpot Stage Checklist",
    ruleKey: "hubspot_stage_transition_checklist",
    endpoint: "/api/integrations/hubspot/stage-checklist",
    runAction: "sync",
    supportsDryRun: true,
    supportsStatusOverride: true,
    editorType: "generic",
    fields: [
      { key: "monitoredPipelines", label: "Monitored Pipelines", type: "string-list", description: "Leave empty to monitor all pipelines." },
      { key: "maxResults", label: "Max Deals Per Run", type: "number", min: 1, max: 500 },
      {
        key: "stageChecklists",
        label: "Stage Checklists",
        type: "stage-checklist-map",
        description:
          "One line per stage: stageId|Stage Label|dueInDays|item1;item2;item3",
      },
    ],
  },
  {
    id: "hubspot-customer-signals",
    provider: "hubspot",
    title: "HubSpot Customer Signals",
    ruleKey: "hubspot_customer_signal_followup",
    endpoint: "/api/integrations/hubspot/customer-signals",
    runAction: "sync",
    supportsDryRun: true,
    supportsStatusOverride: true,
    editorType: "generic",
    fields: [
      { key: "monitoredPipelines", label: "Monitored Pipelines", type: "string-list", description: "Leave empty to monitor all pipelines." },
      { key: "maxResults", label: "Max Deals Per Run", type: "number", min: 1, max: 500 },
      { key: "maxContactsPerDeal", label: "Max Contacts Per Deal", type: "number", min: 1, max: 200 },
      {
        key: "stageSignals",
        label: "Stage Signal Templates",
        type: "signal-template-map",
        description:
          "One line per signal: signalKey|Label|dueInDays|Priority(P0-P3)|action1;action2",
      },
      {
        key: "contactLifecycleSignals",
        label: "Contact Lifecycle Signal Templates",
        type: "signal-template-map",
        description:
          "One line per signal: signalKey|Label|dueInDays|Priority(P0-P3)|action1;action2",
      },
    ],
  },
  {
    id: "hubspot-risk-intervention",
    provider: "hubspot",
    title: "HubSpot Risk Intervention",
    ruleKey: "hubspot_stale_risk_intervention",
    endpoint: "/api/integrations/hubspot/risk-intervention",
    runAction: "sync",
    supportsDryRun: true,
    supportsStatusOverride: true,
    editorType: "generic",
    fields: [
      { key: "monitoredPipelines", label: "Monitored Pipelines", type: "string-list", description: "Leave empty to monitor all pipelines." },
      { key: "maxResults", label: "Max Deals Per Run", type: "number", min: 1, max: 500 },
      { key: "staleDaysThreshold", label: "Stale Days Threshold", type: "number", min: 1, max: 120 },
      { key: "closeDateSlipDays", label: "Close Date Slip Days", type: "number", min: 1, max: 120 },
      { key: "healthScoreThreshold", label: "Health Score Threshold", type: "number", min: 0, max: 100 },
      {
        key: "escalateToActiveRiskTypes",
        label: "Risk Types Escalated To ACTIVE",
        type: "enum-list",
        options: [
          { label: "stale", value: "stale" },
          { label: "close_date_slip", value: "close_date_slip" },
          { label: "health_drop", value: "health_drop" },
        ],
      },
    ],
  },
  {
    id: "hubspot-bidirectional-sync",
    provider: "hubspot",
    title: "HubSpot Bidirectional Sync",
    ruleKey: "hubspot_bidirectional_sync",
    endpoint: "/api/integrations/hubspot/bidirectional-sync",
    runAction: "sync",
    supportsDryRun: true,
    supportsStatusOverride: false,
    editorType: "generic",
    fields: [
      { key: "monitoredPipelines", label: "Monitored Pipelines", type: "string-list", description: "Leave empty to monitor all pipelines." },
      { key: "maxResults", label: "Max Records Per Run", type: "number", min: 25, max: 500 },
      {
        key: "conflictResolution",
        label: "Conflict Resolution",
        type: "enum",
        options: [
          { label: "Newest wins", value: "newest_wins" },
          { label: "HubSpot wins", value: "hubspot_wins" },
          { label: "Task wins", value: "task_wins" },
        ],
      },
      {
        key: "taskStatusToDealStage",
        label: "Task Status -> HubSpot Deal Stage",
        type: "task-status-map",
      },
      {
        key: "dealStageToTaskStatus",
        label: "HubSpot Deal Stage -> Task Status",
        type: "string-status-map",
      },
    ],
  },
  {
    id: "slack-status-sync",
    provider: "slack",
    title: "Slack Status Thread Sync",
    ruleKey: "slack_status_thread_sync",
    endpoint: "/api/integrations/slack/status-sync",
    runAction: "sync",
    supportsDryRun: true,
    supportsStatusOverride: true,
    editorType: "generic",
    fields: [
      {
        key: "statusesToSync",
        label: "Statuses To Sync",
        type: "enum-list",
        options: [
          { label: "ACTIVE", value: "ACTIVE" },
          { label: "NOT_DONE", value: "NOT_DONE" },
          { label: "DONE", value: "DONE" },
        ],
      },
      { key: "maxTransitionsPerRun", label: "Max Transitions Per Run", type: "number", min: 1, max: 500 },
      {
        key: "statusMessages",
        label: "Status Message Templates",
        type: "status-message-map",
      },
    ],
  },
  {
    id: "slack-unanswered-requests",
    provider: "slack",
    title: "Slack Unanswered Request Detector",
    ruleKey: "slack_unanswered_request_detector",
    endpoint: "/api/integrations/slack/unanswered-requests",
    runAction: "sync",
    supportsDryRun: true,
    supportsStatusOverride: true,
    editorType: "generic",
    fields: [
      { key: "channelIds", label: "Channel IDs", type: "string-list", description: "One channel ID per line." },
      { key: "requestPatterns", label: "Request Patterns (regex/string)", type: "string-list", description: "One pattern per line." },
      { key: "slaMinutes", label: "SLA Minutes", type: "number", min: 1, max: 10080 },
      { key: "maxMessagesPerChannel", label: "Max Messages Per Channel", type: "number", min: 1, max: 500 },
      { key: "triageDueMinutes", label: "Triage Due Minutes", type: "number", min: 1, max: 10080 },
      { key: "assigneeUserId", label: "Assignee User ID", type: "text" },
    ],
  },
  {
    id: "slack-thread-capture",
    provider: "slack",
    title: "Slack Thread Capture",
    ruleKey: "slack_thread_capture",
    endpoint: "/api/integrations/slack/thread-capture",
    runAction: "capture",
    supportsDryRun: false,
    supportsStatusOverride: true,
    editorType: "thread-capture",
    fields: [
      { key: "triggerReactions", label: "Trigger Reactions", type: "string-list", description: "One reaction (without colons) per line." },
      { key: "allowShortcutTrigger", label: "Allow Shortcut Trigger", type: "boolean" },
    ],
  },
  {
    id: "slack-channel-routing",
    provider: "slack",
    title: "Slack Channel Routing",
    ruleKey: "slack_channel_routing",
    endpoint: "/api/integrations/slack/channel-routing",
    runAction: null,
    supportsDryRun: false,
    supportsStatusOverride: false,
    editorType: "channel-routing",
    fields: [
      { key: "defaultChannelId", label: "Default Channel ID", type: "text" },
      { key: "fallbackToDm", label: "Fallback To DM", type: "boolean" },
    ],
  },
  {
    id: "coda-row-sync",
    provider: "coda",
    title: "Coda Row Sync",
    ruleKey: "coda_row_task_upsert",
    endpoint: "/api/integrations/coda/row-sync",
    runAction: "sync",
    supportsDryRun: true,
    supportsStatusOverride: true,
    editorType: "generic",
    fields: [
      { key: "docId", label: "Doc ID", type: "text" },
      { key: "tableId", label: "Table ID", type: "text" },
      { key: "titleColumn", label: "Title Column", type: "text" },
      { key: "notesColumn", label: "Notes Column", type: "text" },
      { key: "dueColumn", label: "Due Column", type: "text" },
      { key: "ownerColumn", label: "Owner Column", type: "text" },
      { key: "maxRows", label: "Max Rows", type: "number", min: 1, max: 500 },
    ],
  },
  {
    id: "coda-dependency-gates",
    provider: "coda",
    title: "Coda Dependency Gates",
    ruleKey: "coda_dependency_gate_automation",
    endpoint: "/api/integrations/coda/dependency-gates",
    runAction: "sync",
    supportsDryRun: true,
    supportsStatusOverride: true,
    editorType: "generic",
    fields: [
      { key: "docId", label: "Doc ID", type: "text" },
      { key: "tableId", label: "Table ID", type: "text" },
      { key: "taskIdColumn", label: "Task ID Column", type: "text" },
      { key: "gateStatusColumn", label: "Gate Status Column", type: "text" },
      { key: "prerequisiteColumn", label: "Prerequisite Column", type: "text" },
      { key: "blockerColumn", label: "Blocker Column", type: "text" },
      { key: "reasonColumn", label: "Reason Column", type: "text" },
      { key: "maxRows", label: "Max Rows", type: "number", min: 1, max: 500 },
      { key: "advanceStates", label: "Advance States", type: "string-list" },
      { key: "blockedStates", label: "Blocked States", type: "string-list" },
      { key: "advanceToStatus", label: "Advance To Status", type: "enum", options: [...TASK_STATUS_OPTIONS] },
      { key: "blockedToStatus", label: "Blocked To Status", type: "enum", options: [...TASK_STATUS_OPTIONS] },
    ],
  },
  {
    id: "coda-decision-actions",
    provider: "coda",
    title: "Coda Decision Actions",
    ruleKey: "coda_decision_action_converter",
    endpoint: "/api/integrations/coda/decision-actions",
    runAction: "sync",
    supportsDryRun: true,
    supportsStatusOverride: true,
    editorType: "generic",
    fields: [
      { key: "docId", label: "Doc ID", type: "text" },
      { key: "tableId", label: "Table ID", type: "text" },
      { key: "actionColumn", label: "Action Column", type: "text" },
      { key: "decisionColumn", label: "Decision Column", type: "text" },
      { key: "contextColumn", label: "Context Column", type: "text" },
      { key: "dueColumn", label: "Due Column", type: "text" },
      { key: "ownerColumn", label: "Owner Column", type: "text" },
      { key: "maxRows", label: "Max Rows", type: "number", min: 1, max: 500 },
    ],
  },
  {
    id: "pylon-conversation-sync",
    provider: "pylon",
    title: "Pylon Conversation Sync",
    ruleKey: "pylon_conversation_sync",
    endpoint: "/api/integrations/pylon/conversation-sync",
    runAction: "sync",
    supportsDryRun: true,
    supportsStatusOverride: true,
    editorType: "generic",
    fields: [
      { key: "rangePreset", label: "Range", type: "enum", options: [...RANGE_PRESET_OPTIONS] },
      { key: "contextKey", label: "Context Key", type: "text" },
    ],
  },
  {
    id: "pylon-issue-task-sync",
    provider: "pylon",
    title: "Pylon Issues → Task Sync",
    ruleKey: "pylon_issue_task_sync",
    endpoint: "/api/integrations/pylon/issue-task-sync",
    runAction: "sync",
    supportsDryRun: true,
    supportsStatusOverride: true,
    editorType: "generic",
    fields: [
      { key: "rangePreset", label: "Range", type: "enum", options: [...RANGE_PRESET_OPTIONS] },
      { key: "onlyUrgent", label: "Only Urgent", type: "boolean" },
      { key: "includeTags", label: "Include Tags", type: "string-list", description: "One tag per line." },
      { key: "excludeTags", label: "Exclude Tags", type: "string-list", description: "One tag per line." },
      { key: "defaultTaskStatus", label: "Default Task Status", type: "enum", options: [...TASK_STATUS_OPTIONS] },
      { key: "pylonStatusToTaskStatus", label: "Pylon Status → Task Status", type: "string-status-map" },
    ],
  },
];

export function descriptorsForProvider(provider: string): RuleDescriptor[] {
  return RULE_DESCRIPTORS.filter((descriptor) => descriptor.provider === provider);
}
